import { cx } from "@/lib/format";
import { SparkIcon } from "./Icons";

/**
 * Says which implementation actually produced the data on screen.
 *
 * The backend returns `generated_by` on every response, and it reports the
 * truth — if an LLM call failed and the deterministic fallback ran, this says
 * so. A demo should never claim to be AI-powered when it quietly wasn't.
 */
export function EngineBadge({
  generatedBy,
  className,
}: {
  generatedBy?: string | null;
  className?: string;
}) {
  if (!generatedBy) return null;

  const isLive = !generatedBy.startsWith("mock");
  const hasLlmPass = generatedBy.includes("+llm");
  const live = isLive || hasLlmPass;

  const label = live
    ? generatedBy.replace("mock-crop-scoring-v0+llm-reasons", "IFM/K2-Think-v2")
    : "built-in heuristic";

  return (
    <span
      className={cx(
        "inline-flex items-center gap-1.5 rounded-pill border px-2.5 py-1 text-[11px] font-medium",
        live
          ? "border-sage-deep bg-sage text-forest"
          : "border-line bg-cream-deep text-ink-faint",
        className,
      )}
      title={`generated_by: ${generatedBy}`}
    >
      {live ? <SparkIcon className="h-3 w-3" /> : null}
      {live ? "Generated by " : "Generated by "}
      <span className="font-semibold">{label}</span>
    </span>
  );
}
