import { cx } from "@/lib/format";
import { SparkIcon } from "./Icons";

/**
 * Says which implementation actually produced the data on screen.
 *
 * The backend returns `generated_by` on every response, and it reports the
 * truth — if an LLM call failed and the deterministic fallback ran, this says
 * so. A demo should never claim to be AI-powered when it quietly wasn't.
 */
/** Model ids are for logs; these are for people. */
const MODEL_NAMES: Record<string, string> = {
  "IFM/K2-Think-v2": "K2 Think",
  "IFM/K2-Horizon-375B-A23B": "K2 Horizon",
};

/**
 * Which model ran is not fixed: if one stops responding the backend fails over
 * to the other, and a per-meal split can land on both, arriving here as "a + b".
 * Name whichever actually answered rather than assuming the usual one.
 */
function modelName(generatedBy: string): string {
  return generatedBy
    .split("+")
    .map((part) => part.trim())
    .map((part) => MODEL_NAMES[part] ?? part)
    .join(" + ");
}

export function EngineBadge({
  generatedBy,
  className,
}: {
  generatedBy?: string | null;
  className?: string;
}) {
  if (!generatedBy) return null;

  const isLive = !generatedBy.startsWith("mock");
  const hasLlmPass = generatedBy.includes("+llm");
  const live = isLive || hasLlmPass;

  // Crop scoring reports its LLM pass without naming the model, and the model
  // that ran is no longer predictable, so credit K2 without inventing which.
  const label = !live
    ? "built-in heuristic"
    : hasLlmPass && !isLive
      ? "K2"
      : modelName(generatedBy);

  return (
    <span
      className={cx(
        "inline-flex items-center gap-1.5 rounded-pill border px-2.5 py-1 text-[11px] font-medium",
        live
          ? "border-sage-deep bg-sage text-forest"
          : "border-line bg-cream-deep text-ink-faint",
        className,
      )}
      title={`generated_by: ${generatedBy}`}
    >
      {live ? <SparkIcon className="h-3 w-3" /> : null}
      {live ? "Generated by " : "Generated by "}
      <span className="font-semibold">{label}</span>
    </span>
  );
}
