"use client";

/**
 * Talk to the garden.
 *
 * Hold the button, say what you want changed, let go. The recording goes to
 * ElevenLabs for transcription, the text is interpreted into validated
 * commands, those are applied to the crop selection, and the layout is
 * regenerated by the ordinary planner — so a spoken edit lands in exactly the
 * same place a clicked one would.
 *
 * Three ways in, in order of preference, because a demo cannot hinge on one
 * API being reachable:
 *   1. ElevenLabs Scribe, when the backend has a key.
 *   2. The browser's own speech recognition, when it has one.
 *   3. The text box, which is always there and always works.
 *
 * Push-to-talk rather than always-listening: a hackathon room is loud, and a
 * mic that opens itself will pick up the person demoing at the next table.
 */

import { useCallback, useRef, useState } from "react";

import { applyCommands, layoutCropsFor, type GardenSelection } from "@/lib/garden-commands";
import { generateLayout } from "@/lib/api";
import { browserSpeechSupported, interpret, listenWithBrowser, transcribeAudio } from "@/lib/voice";
import { useGardenStore } from "@/lib/store";
import { cx } from "@/lib/format";

type Phase = "idle" | "listening" | "thinking" | "planting";

const PHASE_LABEL: Record<Phase, string> = {
  idle: "Hold to talk",
  listening: "Listening…",
  thinking: "Working out what you meant…",
  planting: "Replanting…",
};

export function VoiceGardenControl() {
  const { state, update } = useGardenStore();
  const [phase, setPhase] = useState<Phase>("idle");
  const [transcript, setTranscript] = useState<string>("");
  const [log, setLog] = useState<string[]>([]);
  const [problem, setProblem] = useState<string>("");
  const [typed, setTyped] = useState("");
  const [micUnavailable, setMicUnavailable] = useState(false);

  const recorder = useRef<MediaRecorder | null>(null);
  const chunks = useRef<BlobPart[]>([]);
  // Snapshots for undo. Ten deep is plenty for "no, put it back".
  const history = useRef<GardenSelection[]>([]);

  const regenerate = useCallback(
    async (selection: GardenSelection) => {
      const crops = layoutCropsFor(selection, state.recommendations);
      if (crops.length === 0) {
        update({ ...selection, layout: null });
        return;
      }
      const result = await generateLayout({
        plot: state.space.plot,
        garden_type: state.space.garden_type,
        crops,
      });
      update({ ...selection, layout: result.data, offlineMode: result.usedFallback });
    },
    [state.recommendations, state.space, update],
  );

  /** The one path every input method funnels into. */
  const run = useCallback(
    async (text: string) => {
      setTranscript(text);
      setProblem("");
      setPhase("thinking");

      const result = await interpret(text);
      if (!result || !result.understood) {
        setPhase("idle");
        setProblem(
          result && result.transcript
            ? `Didn't catch a garden change in "${result.transcript}". Try "add basil" or "remove the kale".`
            : "That didn't reach the backend. Is it running?",
        );
        return;
      }

      const current: GardenSelection = {
        selectedCropIds: state.selectedCropIds,
        plantCounts: state.plantCounts,
      };

      // "Undo" is handled here rather than in the reducer: only this component
      // knows what the garden looked like before.
      if (result.commands.some((command) => command.kind === "undo")) {
        const previous = history.current.pop();
        if (!previous) {
          setPhase("idle");
          setProblem("Nothing to undo yet.");
          return;
        }
        setPhase("planting");
        await regenerate(previous);
        setLog((lines) => ["Undid the last change", ...lines].slice(0, 8));
        setPhase("idle");
        return;
      }

      const applied = applyCommands(result.commands, current, state.recommendations);
      if (applied.applied.length === 0) {
        setPhase("idle");
        setProblem(applied.skipped[0] ?? "Nothing changed.");
        return;
      }

      history.current = [current, ...history.current].slice(0, 10);
      setPhase("planting");
      await regenerate({
        selectedCropIds: applied.selectedCropIds,
        plantCounts: applied.plantCounts,
      });
      setLog((lines) => [...applied.applied, ...lines].slice(0, 8));
      if (applied.skipped.length > 0) setProblem(applied.skipped[0]);
      setPhase("idle");
    },
    [regenerate, state.plantCounts, state.recommendations, state.selectedCropIds],
  );

  /* ---- microphone ---- */

  const startListening = useCallback(async () => {
    setProblem("");
    if (!navigator.mediaDevices?.getUserMedia || typeof MediaRecorder === "undefined") {
      setMicUnavailable(true);
      setProblem("This browser has no microphone API — type the request instead.");
      return;
    }
    try {
      const stream = await navigator.mediaDevices.getUserMedia({ audio: true });
      const media = new MediaRecorder(stream);
      chunks.current = [];
      media.ondataavailable = (event) => {
        if (event.data.size > 0) chunks.current.push(event.data);
      };
      media.onstop = async () => {
        stream.getTracks().forEach((track) => track.stop());
        const blob = new Blob(chunks.current, { type: media.mimeType || "audio/webm" });
        if (blob.size < 1200) {
          setPhase("idle");
          setProblem("That was too short to hear. Hold the button while you speak.");
          return;
        }
        setPhase("thinking");
        const result = await transcribeAudio(blob);
        if (result.text) {
          await run(result.text);
          return;
        }
        // ElevenLabs unavailable — try the browser's recogniser before giving up.
        if (browserSpeechSupported()) {
          setProblem("Using this browser's speech recognition instead. Speak now.");
          setPhase("listening");
          const heard = await listenWithBrowser();
          if (heard) {
            await run(heard);
            return;
          }
        }
        setPhase("idle");
        setMicUnavailable(true);
        setProblem(result.error ?? "Couldn't transcribe that — type it instead.");
      };
      media.start();
      recorder.current = media;
      setPhase("listening");
    } catch {
      setMicUnavailable(true);
      setPhase("idle");
      setProblem("Microphone access was blocked — type the request instead.");
    }
  }, [run]);

  const stopListening = useCallback(() => {
    if (recorder.current && recorder.current.state === "recording") {
      recorder.current.stop();
      recorder.current = null;
    }
  }, []);

  const busy = phase === "thinking" || phase === "planting";

  return (
    <section className="card p-5">
      <div className="flex items-baseline justify-between gap-3">
        <h2 className="font-display text-lg text-forest">Change it by voice</h2>
        <span className="text-[11px] text-ink-faint">Hold, speak, release</span>
      </div>

      <p className="mt-1 text-xs leading-relaxed text-ink-muted">
        Try &ldquo;add basil and mint&rdquo;, &ldquo;remove the kale&rdquo;, &ldquo;six
        tomatoes&rdquo;, &ldquo;double the lettuce&rdquo;, or &ldquo;undo&rdquo;.
      </p>

      {!micUnavailable ? (
        <button
          type="button"
          disabled={busy}
          onPointerDown={startListening}
          onPointerUp={stopListening}
          onPointerLeave={stopListening}
          onPointerCancel={stopListening}
          className={cx(
            "mt-4 flex w-full items-center justify-center gap-2 rounded-pill px-5 py-3.5 text-sm font-semibold transition-colors",
            phase === "listening"
              ? "bg-[#C9622F] text-white"
              : busy
                ? "bg-sage text-forest"
                : "bg-forest text-cream",
          )}
        >
          <span
            className={cx(
              "h-2.5 w-2.5 rounded-full",
              phase === "listening" ? "animate-pulse bg-white" : "bg-cream/70",
            )}
            aria-hidden="true"
          />
          {PHASE_LABEL[phase]}
        </button>
      ) : null}

      <form
        className="mt-3 flex gap-2"
        onSubmit={(event) => {
          event.preventDefault();
          const text = typed.trim();
          if (!text || busy) return;
          setTyped("");
          void run(text);
        }}
      >
        <input
          value={typed}
          onChange={(event) => setTyped(event.target.value)}
          placeholder={micUnavailable ? "Type a change…" : "…or type it"}
          className="min-w-0 flex-1 rounded-xl border border-line bg-white px-3 py-2.5 text-sm text-forest placeholder:text-ink-faint"
        />
        <button type="submit" className="btn-secondary !py-2.5" disabled={busy}>
          Apply
        </button>
      </form>

      {transcript ? (
        <p className="mt-3 rounded-xl bg-sage-tint px-3.5 py-2.5 text-sm italic text-forest">
          &ldquo;{transcript}&rdquo;
        </p>
      ) : null}

      {problem ? <p className="mt-2 text-xs text-[#A0522A]">{problem}</p> : null}

      {log.length > 0 ? (
        <ul className="mt-3 space-y-1 border-t border-line pt-3">
          {log.map((line, index) => (
            <li
              key={`${line}-${index}`}
              className={cx("text-xs", index === 0 ? "font-semibold text-forest" : "text-ink-muted")}
            >
              {line}
            </li>
          ))}
        </ul>
      ) : null}
    </section>
  );
}
